Update update_corpus.yml

diff --git a/.github/workflows/update_corpus.yml b/.github/workflows/update_corpus.yml
--- a/.github/workflows/update_corpus.yml
+++ b/.github/workflows/update_corpus.yml
@@ -25,6 +25,9 @@ jobs:
         run: |
           ls -l corpus/
           cat corpus/updated_files_control.csv
+      - name: Run the Python Script with Debugging
+        run: |
+          python script/Resultat_graph.py || echo "Script execution failed!" && exit 1
 
       - name: Run the Python Script
         run: |
